#!/bin/sh
set -eu

# Defaults
STACK_URL="${1:-}"
# Also allow: sh -s -- --url "https://…tar.gz"
if [ "${1:-}" = "--url" ] && [ -n "${2:-}" ]; then
  STACK_URL="$2"
fi

if [ -z "$STACK_URL" ]; then
  echo "Usage: sh mesa-vulkan-upgrade.sh --url <tarball_url>" >&2
  exit 1
fi

SYS_DIR="/userdata/system"
TARGET_DIR_NAME="$(basename "$STACK_URL" .tar.gz)"
TARGET_DIR="$SYS_DIR/$TARGET_DIR_NAME"
TARBALL="$SYS_DIR/$TARGET_DIR_NAME.tar.gz"
CUSTOM_SH="$SYS_DIR/custom.sh"
PROFILE="$SYS_DIR/.profile"

echo "[i] Target stack directory: $TARGET_DIR"
echo "[i] Downloading stack tarball: $STACK_URL"

# Prepare
mkdir -p "$SYS_DIR"
rm -f "$TARBALL"
curl -fL "$STACK_URL" -o "$TARBALL"

echo "[i] Extracting..."
rm -rf "$TARGET_DIR"
mkdir -p "$TARGET_DIR"
tar -xzf "$TARBALL" -C "$TARGET_DIR"
rm -f "$TARBALL"

# Enforce ownership & perms
chown -R root:root "$TARGET_DIR"
chmod 755 "$TARGET_DIR" "$TARGET_DIR/lib" "$TARGET_DIR/icd"
chmod 644 "$TARGET_DIR/icd/"*.json
chmod 755 "$TARGET_DIR/lib/"*.so*

# Install / update persistent env hook
echo "[i] Installing persistent $CUSTOM_SH"
cat > "$CUSTOM_SH" <<'EOF'
#!/bin/sh
# Persistent environment for upgraded Vulkan/Mesa stack (autogenerated)
STACK_DIR="$(ls -1d /userdata/system/mesa-vulkan-* 2>/dev/null | sort | tail -n1)"
if [ -n "$STACK_DIR" ]; then
  export LD_LIBRARY_PATH="$STACK_DIR/lib:/usr/lib"
  export VK_ICD_FILENAMES="$STACK_DIR/icd/broadcom_icd.cortex-a76.json"
fi

# Quiet down xkb compose warnings on ES console
export XCOMPOSEFILE=/dev/null
unset XMODIFIERS

# Restart EmulationStation once at boot to pick env up
LOCK=/var/run/es-vulkan-restart.lock
if [ ! -f "$LOCK" ]; then
  touch "$LOCK"
  if [ -x /etc/init.d/S31emulationstation ]; then
    ( sleep 2; /etc/init.d/S31emulationstation restart ) &
  else
    ( sleep 2; killall emulationstation 2>/dev/null; sleep 2; /usr/bin/emulationstation & ) &
  fi
fi
EOF
chmod 755 "$CUSTOM_SH"
chown root:root "$CUSTOM_SH"

# Ensure .profile sources custom.sh (add once)
if [ ! -f "$PROFILE" ]; then
  : > "$PROFILE"
  chown root:root "$PROFILE"
  chmod 644 "$PROFILE"
fi
grep -q '/userdata/system/custom\.sh' "$PROFILE" 2>/dev/null || {
  echo ". /userdata/system/custom.sh" >> "$PROFILE"
}

echo "[i] Verification:"
# Use the freshly installed stack (current shell)
. "$CUSTOM_SH" >/dev/null 2>&1 || true
vulkaninfo 2>/dev/null | sed -n '1,8p' || true
vulkaninfo 2>/dev/null | awk '/apiVersion|driverVersion|deviceName/{print}' || true

echo
echo "[✓] Done. Persistent env is set via $CUSTOM_SH"
echo "    Stack directory: $TARGET_DIR"

